const artists = [
    {
        id: 1,
        titleName: 'Away',
        name: "Oly Amo",
        picture: "/images/Oly_Amo.jpeg",
        alt: "Ola Amo picture",
        tag: "'From Russia with love (and vodka).'",
        siteLogo: "/images/spotify-logo.jpeg",
        href: 'https://open.spotify.com/artist/2bo68FjQmdPUXPbrxLC2M2',
        work: "Vocals, lyrics, mixing and production on 'Away', 'Weightless' and 'Never Stop Me'",
    },
    {
        id: 2,
        titleName: 'Away',
        name: "Ktm Chano",
        picture: "/images/KTM_Chano.png",
        alt: "Ktm Chano picture",
        tag: "'Just trying to make dreams come true.'",
        siteLogo: "/images/2020_soundcloudlogo.png",
        href: 'https://soundcloud.com/chandler-sutherland',
        work: "Vocals and lyrics on 'Never Stop Me'",
    },
    {
        id: 3,
        titleName: 'Away',
        name: "Chris Shoda",
        picture: "/images/Chris_Shoda.jpeg",
        alt: "Chris Shoda picture",
        tag: "'Pursue your dreams until they pursue you.'",
        siteLogo: "/images/spotify-logo.jpeg",
        href: 'https://open.spotify.com/artist/0ryzMRpTWkUorpPA8CSZ8u?si=QxjyNVXaTgKTwM3l8acr1A',
        work: "Vocals, lyrics, mixing and production on 'Changes'",
    },
    {
        id: 4,
        titleName: 'Away',
        name: "Larsxn",
        picture: "/images/Larsxn_shades_cropped.jpeg",
        alt: "Larsxn picture",
        tag: "'It's got to come from the heart.'",
        siteLogo: "",
        href: '',
        work: "Vocals and lyrics on 'Changes', 'Away', 'Ungrateful', 'Weightless' and 'Never Stop Me'",
        finalComment: "Let's make music."
    },
    {
        id: 5,
        titleName: 'Lie',
        name: "Chris Shoda",
        picture: "/images/Chris_Shoda.jpeg",
        alt: "Chris Shoda picture",
        tag: "'Pursue your dreams until they pursue you.'",
        siteLogo: "/images/spotify-logo.jpeg",
        href: 'https://open.spotify.com/artist/0ryzMRpTWkUorpPA8CSZ8u?si=QxjyNVXaTgKTwM3l8acr1A',
        work: "Vocals, mixing and production on 'Lie'",
    },
    {
        id: 6,
        titleName: 'Lie',
        name: "Larsxn",
        picture: "/images/Larsxn_shades_cropped.jpeg",
        alt: "Larsxn picture",
        tag: "'It's got to come from the heart.'",
        siteLogo: "",
        href: '',
        work: "Vocals and lyrics on 'Lie'",
        finalComment: "Let's make music."
    },
  ];

  export default artists;