const artists = [
    {
        id: 1,
        titleName: 'Away',
        name: "Oly Amo",
        picture: "/images/Oly_Amo.jpeg",
        alt: "Ola Amo picture",
        tag: "'From Russia with love (and vodka).'",
        siteLogo: "/images/spotify-logo.jpeg",
        href: 'https://open.spotify.com/artist/2bo68FjQmdPUXPbrxLC2M2',
        work: "Vocals, lyrics, mixing and production on 'Away', 'Weightless' and 'Never Stop Me'",
    },
    {
        id: 2,
        titleName: 'Away',
        name: "Ktm Chano",
        picture: "/images/KTM_Chano.png",
        alt: "Ktm Chano picture",
        tag: "'Just trying to make dreams come true.'",
        siteLogo: "/images/2020_soundcloudlogo.jpeg",
        href: 'https://soundcloud.com/chandler-sutherland',
        work: "Vocals and lyrics on 'Never Stop Me'",
    },
    {
        id: 3,
        titleName: 'Away',
        name: "Chris Shoda",
        picture: "/images/Chris_Shoda.jpeg",
        alt: "Chris Shoda picture",
        tag: "'Pursue your dreams until they pursue you.'",
        siteLogo: "/images/spotify-logo.jpeg",
        href: 'https://open.spotify.com/artist/3KpwMlf1TsbavQF4O5VmLw',
        work: "Vocals, lyrics, mixing and production on 'Changes'",
    },
    {
        id: 4,
        titleName: 'Away',
        name: "Larsxn",
        picture: "/images/Larsxn_shades_cropped.jpeg",
        alt: "Larsxn picture",
        tag: "'It's got to come from the heart.'",
        siteLogo: "",
        href: '',
        work: "Vocals and lyrics on 'Changes', 'Away', 'Ungrateful', 'Weightless' and 'Never Stop Me'",
        finalComment: "Let's make music."
    },
    {
        id: 5,
        titleName: 'Lie',
        name: "Chris Shoda",
        picture: "/images/Chris_Shoda.jpeg",
        alt: "Chris Shoda picture",
        tag: "'Pursue your dreams until they pursue you.'",
        siteLogo: "/images/spotify-logo.jpeg",
        href: 'https://open.spotify.com/artist/3KpwMlf1TsbavQF4O5VmLw',
        work: "Vocals, mixing and production on 'Lie'",
    },
    {
        id: 6,
        titleName: 'Lie',
        name: "Larsxn",
        picture: "/images/Larsxn_shades_cropped.jpeg",
        alt: "Larsxn picture",
        tag: "'It's got to come from the heart.'",
        siteLogo: "",
        href: '',
        work: "Vocals and lyrics on 'Lie'",
        finalComment: "Let's make music."
    },
    {
        id: 7,
        titleName: 'What Can I Say',
        name: "PLAYD3AD",
        picture: "/images/Playd3ed.jpeg",
        alt: "PLAYD3AD picture",
        tag: "'D3AD4LIFE AND THATS ALL IVE EVER KNOWN'",
        siteLogo: "/images/spotify-logo.jpeg",
        href: 'https://open.spotify.com/artist/4tMwfyckIsnzmaTcZtsFSo',
        work: "Vocals and lyrics on 'What can I say'",
    },
    {
        id: 8,
        titleName: 'What Can I Say',
        name: "Larsxn",
        picture: "/images/Larsxn_shades_cropped.jpeg",
        alt: "Larsxn picture",
        tag: "'It's got to come from the heart.'",
        siteLogo: "",
        href: '',
        work: "Vocals and lyrics on 'What Can I Say'",
        finalComment: "Let's make music."
    },
    {
        id: 9,
        titleName: 'Leave You',
        name: "Chris Shoda",
        picture: "/images/Chris_Shoda.jpeg",
        alt: "Chris Shoda picture",
        tag: "'Pursue your dreams until they pursue you.'",
        siteLogo: "/images/spotify-logo.jpeg",
        href: 'https://open.spotify.com/artist/3KpwMlf1TsbavQF4O5VmLw',
        work: "Vocals, mixing and production on 'Lie'",
    },
    {
        id: 10,
        titleName: 'Leave You',
        name: "Larsxn",
        picture: "/images/Larsxn_shades_cropped.jpeg",
        alt: "Larsxn picture",
        tag: "'It's got to come from the heart.'",
        siteLogo: "",
        href: '',
        work: "Vocals and lyrics on 'Lie'",
        finalComment: "Let's make music."
    },
  ];

  export default artists;